repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
 #    -   id: check-builtin-literals
    -   id: check-case-conflict
#    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0 
    hooks:      
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore 
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
          
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)


-   repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
    -   id: check-poetry
        

-   repo: https://github.com/PrincetonUniversity/blocklint
    rev: v0.2.3
    hooks:
    -   id: blocklint
    
