[tool.commitizen]
name = "cz_conventional_commits"
version = ""
version_files = []
tag_format = ""
update_changelog_on_bump = false
annotated_tag = false
bump_message = ""
changelog_file = ""
changelog_incremental = false
changelog_start_rev = ""
customize = {}
use_shortcuts = false

style = [
    ["qmark", "fg:#ff9d00 bold"],
    ["question", "bold"],
    ["answer", "fg:#ff9d00 bold"],
    ["pointer", "fg:#ff9d00 bold"],
    ["highlighted", "fg:#ff9d00 bold"],
    ["selected", "fg:#cc5454"],
    ["separator", "fg:#cc5454"],
    ["instruction", ""],
    ["text", ""],
    ["disabled", "fg:#858585 italic"]
]
