[tool.mypy]
python_version = {{ cookiecutter.project_python_version }}
check_untyped_defs = true
strict_optional = true
warn_unused_configs = true
pretty = true
color_output = true
plugins = "pydantic.mypy"
disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
