[tool.pytest.ini_options]
addopts = ""
# cache_dir = ""
console_output_style = "progress"
# doctest_encoding = ""
# doctest_optionflags = ""
empty_parameter_set_mark = "xfail"
# faulthandler_timeout = ""
# filterwarnings = ""
junit_duration_report = "total"
junit_family = "xunit2"
junit_logging = "all"
junit_log_passing_tests = true
# junit_suite_name = ""
log_auto_indent = true
log_cli = true
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_cli_format = "%(asctime)s [%(levelname)8s] %(name)s: %(message)s (%(filename)s:%(lineno)s)"
log_cli_level = "INFO"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_file = "../logs/pytest-logs.txt"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
log_file_format = "%(asctime)s [%(levelname)8s] %(name)s: %(message)s (%(filename)s:%(lineno)s)" 
log_file_level = "INFO"
log_format = "%(asctime)s [%(levelname)8s] %(name)s: %(message)s (%(filename)s:%(lineno)s)"
log_level = "INFO"
# markers = ""
minversion = "7.1"
norecursedirs = [".git", ".vscode"]
# python_classes = []
python_files = ["test_*.py", "*_test.py", "check_*.py", "*_check.py", "example_*.py", "*_example.py"]
python_functions = ["*_test"]
# pythonpath = []
# required_plugins = []
testpaths = ["tests", "docs"]
# usefixtures = []
xfail_strict = false
