[tool.flake8]
max-line-length = 88
select = ["C, E, F, W, B, B950"]
extend-ignore = ["E203, E501"]


[tool.flakeheaven]
max_line_length = 88
format = "grouped"
show_source = true


[tool.flakeheaven.plugins]
cohesion = ["+*"]
darglint = ["+*"]
dlint = ["+*"]
flake8-annotations = ["+*"]
flake8-bandit = ["+*"]
flake8-broken-line = ["+*"]
flake8-bugbear = ["+*"]
flake8-builtins = ["+*"]
flake8-coding = ["+*"]
flake8-comprehensions = ["+*"]
flake8-dashboard = ["+*"]
flake8-debugger = ["+*"]
flake8-docstrings = ["+*"]
flake8-eradicate = ["+*"]
flake8-executable = ["+*"]
flake8-fixme = ["+*"]
flake8-functions-names = ["+*"]
flake8-logging-format = ["+*"]
flake8-multiline-containers = ["+*"]
flake8-pep3101 = ["+*"]
flake8-pie = ["+*"]
flake8-pytest-style = ["+*"]
flake8-return = ["+*"]
flake8-rst = ["+*"]
flake8-rst-docstrings = ["+*"]
flake8-quotes = ["+*"]
flake8-simplify = ["+*"]
flake8-sql = ["+*"]
flake8-todos = ["+*"]
flake8-type-checking = ["+*"]
flake8-variables-names = ["+*"]
pandas-vet = ["+*"]
pycodestyle = ["+*"]
pyflakes = ["+*", "-F401"]
pylint = ["+*"]





