[tool.isort]
profile = "black"
line_length = 88
include_trailing_comma = true
use_parentheses = true
force_single_line = true
force_sort_within_sections = true
lexicographical = false
single_line_exclusion = ['typing',]
group_by_package = true
skip_gitignore = true
skip = []
extend_skip = []
skip_glob = []
extend_skip_blob = []
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
import_heading_future = "Future Compatability"
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third Party"
import_heading_firstparty = "First Party"
import_heading_localfolder = "Local Imports"
known_third_party = []
known_first_party = []
known_local_folder = []
src_paths = ["src", "tests"]
color_output = true
star_first = true

