[tool.pytest.ini_options]
minversion = "7.1"
addopts = ""
testpaths = ["tests", "docs"]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(name)s: %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_file = "../logs/pytest-logs.txt"
console_output_style = "progress"
